server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "http://localhost:3001"
              - "http://127.0.0.1:3000"
              - "http://127.0.0.1:3001"
              - "https://www.google.com"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: security-auth-route
          uri: lb://FINDU-SPRING-SECURITY
          predicates:
            - Path=/security-auth/**
        - id: authorization-server-route
          uri: lb://AUTORIZATION-SERVER-OAUTH2
          predicates:
            - Path=/authorization-server/**
        - id: findu-core-route
          uri: lb://FINDU-CORE
          predicates:
            - Path=/findu-core/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: health, gateway, info
