server:
  port: 8084

spring:
  application:
    name: findu-transaction
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
