spring:
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:postgresql://postgres-security-prod:5432/findu}
    username: ${SPRING_R2DBC_USERNAME:findu}
    password: ${SPRING_R2DBC_PASSWORD:findu}

findu:
  deployment: prod
  aws:
    dynamodb:
      enabled: true
