spring:
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:postgresql://postgres-security:5432/findu}
    username: ${SPRING_R2DBC_USERNAME:findu}
    password: ${SPRING_R2DBC_PASSWORD:findu}

findu:
  deployment: dev
  aws:
    dynamodb:
      enabled: ${FINDU_AWS_DYNAMODB_ENABLED:false}
