-- PostgreSQL: esquema FINDU.
-- Ejecutar tras crear la base, p. ej.: CREATE DATABASE findu OWNER tu_usuario;
-- Orden: hijos antes que padres al DROP.

DROP TABLE IF EXISTS user_identity_provider;
DROP TABLE IF EXISTS user_rol;
DROP TABLE IF EXISTS rol_operation;
DROP TABLE IF EXISTS password_recovery_token;
DROP TABLE IF EXISTS password_recovery_code;
DROP TABLE IF EXISTS "user";
DROP TABLE IF EXISTS operation;
DROP TABLE IF EXISTS role;
DROP TABLE IF EXISTS module;

CREATE TABLE module (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(25) NOT NULL,
    path_base VARCHAR(64) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    CONSTRAINT uq_module_name UNIQUE (name)
);

CREATE TABLE operation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    path VARCHAR(255) NOT NULL,
    name VARCHAR(64),
    http_method VARCHAR(10) NOT NULL,
    module_id BIGINT NOT NULL,
    permite_all BOOLEAN NOT NULL DEFAULT FALSE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    CONSTRAINT fk_operation_module FOREIGN KEY (module_id) REFERENCES module(id),
    CONSTRAINT uq_operation_name UNIQUE (name),
    CONSTRAINT uq_operation_module_path_method UNIQUE (module_id, path, http_method)
);

CREATE TABLE role (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    CONSTRAINT uq_role_name UNIQUE (name)
);

CREATE TABLE rol_operation (
    role_id INT NOT NULL,
    operation_id BIGINT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    PRIMARY KEY (role_id, operation_id),
    CONSTRAINT fk_rol_operation_role FOREIGN KEY (role_id) REFERENCES role(id),
    CONSTRAINT fk_rol_operation_operation FOREIGN KEY (operation_id) REFERENCES operation(id)
);

CREATE TABLE "user" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone VARCHAR(20),
    cod_phone_international VARCHAR(10) DEFAULT '+57',
    username VARCHAR(50) NOT NULL,
    password VARCHAR(200),
    email VARCHAR(200) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    CONSTRAINT uq_user_email UNIQUE (email),
    CONSTRAINT uq_user_username UNIQUE (username),
    CONSTRAINT uq_user_phone UNIQUE (phone)
);

CREATE TABLE user_identity_provider (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    provider_name VARCHAR(50) NOT NULL, -- 'google', 'apple'
    provider_user_id VARCHAR(100) NOT NULL, -- ID único del proveedor (sub)
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_identity_user FOREIGN KEY (user_id) REFERENCES "user"(id),
    CONSTRAINT uq_user_provider UNIQUE (provider_name, provider_user_id)
);

CREATE TABLE password_recovery_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token VARCHAR(64) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    used BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_recovery_token_user FOREIGN KEY (user_id) REFERENCES "user"(id),
    CONSTRAINT uq_recovery_token UNIQUE (token)
);

CREATE TABLE password_recovery_code (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    code VARCHAR(100) NOT NULL,
    emitted_at BIGINT NOT NULL,
    expires_at BIGINT NOT NULL,
    used BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_recovery_code_user FOREIGN KEY (user_id) REFERENCES "user"(id)
);


CREATE TABLE user_rol (
    role_id INT NOT NULL,
    user_id BIGINT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    PRIMARY KEY (role_id, user_id),
    CONSTRAINT fk_user_rol_role FOREIGN KEY (role_id) REFERENCES role(id),
    CONSTRAINT fk_user_rol_user FOREIGN KEY (user_id) REFERENCES "user"(id)
);
