spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/findu_oauth2}
    username: ${SPRING_DATASOURCE_USERNAME:findu_oauth2}
    password: ${SPRING_DATASOURCE_PASSWORD:findu_oauth2_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
      data-locations: classpath:db/postgres/data.sql

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
